e_bedding/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_bedding.Models;

namespace e_bedding.Controllers
{
    public class ChartController : Controller
    {
        private readonly e_beddingContext _context;

        public ChartController(e_beddingContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Manage()
        {
            return View(await _context.ChartModel.ToListAsync());
        }

        // GET: Chart
        public async Task<IActionResult> Index()
        {
            int var;
            var = int.Parse(DateTime.Now.ToString("yMddmmss"));
            var = var + 16666;
            ViewData["ReleasedID"] = var.ToString();
            String date = DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss");
            ViewData["ReleasedTime"] = date;
            return View(await _context.ChartModel.ToListAsync());
        }

        // GET: Chart/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chartModel == null)
            {
                return NotFound();
            }

            return View(chartModel);
        }

        // GET: Chart/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chart/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chartModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        // GET: Chart/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel.FindAsync(id);
            if (chartModel == null)
            {
                return NotFound();
            }
            return View(chartModel);
        }

        // POST: Chart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            if (id != chartModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chartModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChartModelExists(chartModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        // GET: Chart/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chartModel == null)
            {
                return NotFound();
            }

            return View(chartModel);
        }

        // POST: Chart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chartModel = await _context.ChartModel.FindAsync(id);
            _context.ChartModel.Remove(chartModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChartModelExists(int id)
        {
            return _context.ChartModel.Any(e => e.ID == id);
        }


        //      ID: index,
        //          ItemName: itemname,
        //        Specification: sepc,
        //        Quantity: qty,
        //        Price: (prc* qty).toFixed(2),
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int ID,[Bind("ID,ItemID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            //if (ID == chartModel.ID)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        try
            //        {
            //            _context.Update(chartModel);
            //            await _context.SaveChangesAsync();
            //        }
            //        catch (DbUpdateConcurrencyException)
            //        {
            //            if (!ChartModelExists(chartModel.ID))
            //            {
            //                return NotFound();
            //            }
            //            else
            //            {
            //                throw;
            //            }
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    return View(chartModel);
            //}
            if (ModelState.IsValid)
            {
                _context.Add(chartModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        //public IActionResult Get(int id, String ItemName, String Specification, int Quantity, float Price)
        //{
        //    //Flower = await _context.Flower.ToListAsync();
        //    //var _items = from i in _context.Items
        //    //             select i;
        //    //var _item = _items.Where(x => x.ID == id);
        //    //var items = await _item.ToListAsync();
        //    ViewData["msg"] = Quantity + " " + Specification + " " + ItemName + " are " + Price;
        //    return View();
        //}
    }
}

e_bedding/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using e_bedding.Models;

namespace e_bedding.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "This the description of ebedding";

            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Manage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

e_bedding/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_bedding.Models;

namespace e_bedding.Controllers
{
    public class ItemsController : Controller
    {
        private readonly e_beddingContext _context;

        public ItemsController(e_beddingContext context)
        {
            _context = context;
        }
        public IList<ItemsModel> ITems { get; set; }
        public SelectList Types { get; set; }
        public string itemTypes { get; set; }
        public string SearchString { get; set; }

        public async Task<IActionResult> Manage()
        {
            return View(await _context.Items.ToListAsync());
        }

        // GET: Items/?category=id
        public async Task<IActionResult> Index(string category, string itemsType)
        { //string searchString, string itemType
          //
            if (String.IsNullOrEmpty(category))
            {
                ViewData["Message"] = "All eBedding Items";
            }
            else
            {
                ViewData["Message"] = "The " + category;
            }
            IQueryable<string> TypeQuery = from m in _context.Items
                                           orderby m.Band
                                           select m.Band;
            //Flower = await _context.Flower.ToListAsync();
            var ebditems = from m in _context.Items
                           select m;

            if (!String.IsNullOrEmpty(category))
            {
                ebditems = ebditems.Where(s => s.Type.Contains(category));
            }
            if (!String.IsNullOrEmpty(itemsType))
            {
                ebditems = ebditems.Where(x => x.Band == itemsType);
            }

            IEnumerable<SelectListItem> eitems = new SelectList(await TypeQuery.Distinct().ToListAsync());
            ViewBag.itemsType = eitems;
            ViewData["category"] = category;
            return View(await ebditems.ToListAsync());
        }



        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemsModel = await _context.Items
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemsModel == null)
            {
                return NotFound();
            }

            return View(itemsModel);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ItemName,Type,Color,Band,Price,Description,photo_url")] ItemsModel itemsModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(itemsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(itemsModel);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemsModel = await _context.Items.FindAsync(id);
            if (itemsModel == null)
            {
                return NotFound();
            }
            return View(itemsModel);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemName,Type,Color,Band,Price,Description,photo_url")] ItemsModel itemsModel)
        {
            if (id != itemsModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemsModelExists(itemsModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemsModel);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemsModel = await _context.Items
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemsModel == null)
            {
                return NotFound();
            }

            return View(itemsModel);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var itemsModel = await _context.Items.FindAsync(id);
            _context.Items.Remove(itemsModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("ID,ItemName,Specification,Quantity,Price")] ChartModel chartModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chartModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        private bool ItemsModelExists(int id)
        {
            return _context.Items.Any(e => e.ID == id);
        }

        private bool ChartModelExists(int id)
        {
            return _context.ChartModel.Any(e => e.ID == id);
        }

    }
}

e_bedding/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>The Description</p>

e_bedding/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .photos {
    text-align:center;
    }
</style>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/1.jpg" alt="ASP.NET" class="img-responsive" 
                 style="background-size: cover; background-position: center top; width: 1300px; height: 495px;"
                 />
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src="~/images/2.jpg" alt="Visual Studio" class="img-responsive" 
                 style="background-size: cover; background-position: center top; width: 1300px; height: 495px;"
                 />
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src="~/images/3.jpg" alt="Microsoft Azure" class="img-responsive" 
                  style="background-size: cover; background-position: center top; width: 1200px; height: 495px;"
                 />
            <div class="carousel-caption" role="option">
             </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <br>
        <img src="//www.e-bedding.co.uk/wp-content/uploads/2016/07/pillows-4.jpg" alt="Plz refresh to reload photo" width="262" height="262">
        <br>
        <p class="photos"><a asp-area="" asp-controller="Items" asp-action="Index" asp-route-category="Pillow" asp-route-itemband="">PILLOWS</a></p>
    </div>    
    <div class="col-md-3">
        <br>
        <img src="//www.e-bedding.co.uk/wp-content/uploads/2016/11/Refinery-So-Soft-Duvet.jpg" alt="Plz refresh to reload photo" width="262" height="262">
        <br>
        <p class="photos"><a asp-area="" asp-controller="Items" asp-action="Index" asp-route-category="Duvet"  asp-route-itemband="">DUVETS</a></p>
</div>
    <div class="col-md-3">
        <br>
        <img src="//www.e-bedding.co.uk/wp-content/uploads/2016/11/Refinery-Sealy-Response-Topper.jpg" alt="Plz refresh to reload photo" width="262" height="262">
        <br>
        <p class="photos"><a asp-area="" asp-controller="Items" asp-action="Index" asp-route-category="Topper"  asp-route-itemband="">TOPPERS</a></p>
</div>    
    <div class="col-md-3">
        <br>
        <img src="//www.e-bedding.co.uk/wp-content/uploads/2016/11/butterfly-lace-no-usm.jpg" alt="Plz refresh to reload photo" width="262" height="262">
        <br>
        <p class="photos"><a asp-area="" asp-controller="Items" asp-action="Index" asp-route-category="Bedding"  asp-route-itemband="">BEDDING</a></p>
</div>
</div>

<div style="float:right;font-size:larger"><a asp-area="" asp-controller="Items" asp-action="Index">View All</a></div>

e_bedding/Views/Home/Manage.cshtml
<h2>Admin Management Page</h2>
<ul>
    <li><a asp-area="" asp-controller="Items" asp-action="Manage">Manage items</a></li>
    <li><a asp-area="" asp-controller="Chart" asp-action="Manage">Manage Chart</a></li>
    <li><a asp-area="" asp-controller="Report" asp-action="Manage">Manage Report</a></li>
    <li><a asp-area="" asp-controller="UploadFiles" asp-action="Upload">Manage resources</a></li>
 </ul>