e_bedding/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_bedding.Models;

namespace e_bedding.Controllers
{
    public class ChartController : Controller
    {
        private readonly e_beddingContext _context;

        public ChartController(e_beddingContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Manage()
        {
            return View(await _context.ChartModel.ToListAsync());
        }

        // GET: Chart
        public async Task<IActionResult> Index()
        {
            int var;
            var = int.Parse(DateTime.Now.ToString("yMddmmss"));
            var = var + 16666;
            ViewData["ReleasedID"] = var.ToString();
            String date = DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss");
            ViewData["ReleasedTime"] = date;
            return View(await _context.ChartModel.ToListAsync());
        }

        // GET: Chart/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chartModel == null)
            {
                return NotFound();
            }

            return View(chartModel);
        }

        // GET: Chart/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chart/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chartModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        // GET: Chart/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel.FindAsync(id);
            if (chartModel == null)
            {
                return NotFound();
            }
            return View(chartModel);
        }

        // POST: Chart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            if (id != chartModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chartModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChartModelExists(chartModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        // GET: Chart/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chartModel = await _context.ChartModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chartModel == null)
            {
                return NotFound();
            }

            return View(chartModel);
        }

        // POST: Chart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chartModel = await _context.ChartModel.FindAsync(id);
            _context.ChartModel.Remove(chartModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChartModelExists(int id)
        {
            return _context.ChartModel.Any(e => e.ID == id);
        }


        //      ID: index,
        //          ItemName: itemname,
        //        Specification: sepc,
        //        Quantity: qty,
        //        Price: (prc* qty).toFixed(2),
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int ID,[Bind("ID,ItemID,ItemName,Specification,Quantity,Price,userEmail")] ChartModel chartModel)
        {
            //if (ID == chartModel.ID)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        try
            //        {
            //            _context.Update(chartModel);
            //            await _context.SaveChangesAsync();
            //        }
            //        catch (DbUpdateConcurrencyException)
            //        {
            //            if (!ChartModelExists(chartModel.ID))
            //            {
            //                return NotFound();
            //            }
            //            else
            //            {
            //                throw;
            //            }
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    return View(chartModel);
            //}
            if (ModelState.IsValid)
            {
                _context.Add(chartModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chartModel);
        }

        //public IActionResult Get(int id, String ItemName, String Specification, int Quantity, float Price)
        //{
        //    //Flower = await _context.Flower.ToListAsync();
        //    //var _items = from i in _context.Items
        //    //             select i;
        //    //var _item = _items.Where(x => x.ID == id);
        //    //var items = await _item.ToListAsync();
        //    ViewData["msg"] = Quantity + " " + Specification + " " + ItemName + " are " + Price;
        //    return View();
        //}
    }
}

e_bedding/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_bedding.Models;

namespace e_bedding.Controllers
{
    public class ReportController : Controller
    {
        private readonly e_beddingContext _context;

        public ReportController(e_beddingContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Manage()
        {
            return View(await _context.ReportModel.ToListAsync());
        }

        // GET: Report
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReportModel.ToListAsync());
        }

        // GET: Report/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportModel = await _context.ReportModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (reportModel == null)
            {
                return NotFound();
            }

            return View(reportModel);
        }

        // GET: Report/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Report/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,PaymentMethod,Price,ReleasedTime,userEmail")] ReportModel reportModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportModel);
        }

        // GET: Report/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportModel = await _context.ReportModel.FindAsync(id);
            if (reportModel == null)
            {
                return NotFound();
            }
            return View(reportModel);
        }

        // POST: Report/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,PaymentMethod,Price,ReleasedTime,userEmail")] ReportModel reportModel)
        {
            if (id != reportModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportModelExists(reportModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportModel);
        }

        // GET: Report/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportModel = await _context.ReportModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (reportModel == null)
            {
                return NotFound();
            }

            return View(reportModel);
        }

        // POST: Report/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportModel = await _context.ReportModel.FindAsync(id);
            _context.ReportModel.Remove(reportModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportModelExists(int id)
        {
            return _context.ReportModel.Any(e => e.ID == id);
        }
    }
}

e_bedding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e-Bedding Selling System</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">e-Bedding Selling System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*<li><a asp-area="" asp-controller="Chart" asp-action="Index">Chart</a></li>
                    <li><a asp-area="" asp-controller="Report" asp-action="Index">Payment History</a></li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>*@
                </ul>
                <partial name="_LoginMenu" />
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; 2019 e-Bedding Selling Platform - DDAC Project TP039809</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

e_bedding/Views/Shared/_LoginMenu.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
<ul class="nav navbar-nav">
    <li><a asp-area="Identity" asp-controller="Chart" asp-action="Index">Chart</a></li>
    <li><a asp-area="Identity" asp-controller="Report" asp-action="Index">Payment History</a></li>
</ul>
    }
    else
    {
    <ul class="nav navbar-nav">
        <li>@*<a asp-area="Identity" asp-page="/Account/Register">About</a>*@</li>
        <li><a asp-area="Identity" asp-controller="Home" asp-action="About">About</a></li>
    </ul>
    }